export const DICCIONARIO_CV = {
  'nfeProc.@versao': 'Versão do Processo',
  'nfeProc.NFe.Signature.KeyInfo.X509Data.X509Certificate': 'Certificado X509',
  'nfeProc.NFe.Signature.SignatureValue': 'Valor da Assinatura',
  'nfeProc.NFe.Signature.SignedInfo.CanonicalizationMethod.@Algorithm': 'Algoritmo de Canonicalização',
  'nfeProc.NFe.Signature.SignedInfo.Reference.@URI': 'URI da Referência',
  'nfeProc.NFe.Signature.SignedInfo.Reference.DigestMethod.@Algorithm': 'Algoritmo de Digestão',
  'nfeProc.NFe.Signature.SignedInfo.Reference.DigestValue': 'Valor de Digestão',
  'nfeProc.NFe.Signature.SignedInfo.Reference.Transforms.Transform.@Algorithm': 'Algoritmo de Transformação',
  'nfeProc.NFe.Signature.SignedInfo.SignatureMethod.@Algorithm': 'Método de Assinatura',
  'nfeProc.NFe.infNFe.@Id': 'ID da NF-e',
  'nfeProc.NFe.infNFe.@versao': 'Versão da NF-e',
  'nfeProc.NFe.infNFe.cobr.dup.dVenc': 'Data de Vencimento (Duplicata)',
  'nfeProc.NFe.infNFe.cobr.dup.nDup': 'Número da Duplicata',
  'nfeProc.NFe.infNFe.cobr.dup.vDup': 'Valor da Duplicata',
  'nfeProc.NFe.infNFe.cobr.fat.nFat': 'Número da Fatura',
  'nfeProc.NFe.infNFe.cobr.fat.vDesc': 'Desconto da Fatura',
  'nfeProc.NFe.infNFe.cobr.fat.vLiq': 'Valor Líquido da Fatura',
  'nfeProc.NFe.infNFe.cobr.fat.vOrig': 'Valor Original da Fatura',
  'nfeProc.NFe.infNFe.dest.CNPJ': 'CNPJ Destinatário',
  'nfeProc.NFe.infNFe.dest.IE': 'IE Destinatário',
  'nfeProc.NFe.infNFe.dest.email': 'Email Destinatário',
  'nfeProc.NFe.infNFe.dest.enderDest.CEP': 'CEP Destinatário',
  'nfeProc.NFe.infNFe.dest.enderDest.UF': 'UF Destinatário',
  'nfeProc.NFe.infNFe.dest.enderDest.cMun': 'Município Destinatário',
  'nfeProc.NFe.infNFe.dest.enderDest.cPais': 'País Destinatário',
  'nfeProc.NFe.infNFe.dest.enderDest.fone': 'Telefone Destinatário',
  'nfeProc.NFe.infNFe.dest.enderDest.nro': 'Número Destinatário',
  'nfeProc.NFe.infNFe.dest.enderDest.xBairro': 'Bairro Destinatário',
  'nfeProc.NFe.infNFe.dest.enderDest.xCpl': 'Complemento Destinatário',
  'nfeProc.NFe.infNFe.dest.enderDest.xLgr': 'Logradouro Destinatário',
  'nfeProc.NFe.infNFe.dest.enderDest.xMun': 'Cidade Destinatário',
  'nfeProc.NFe.infNFe.dest.enderDest.xPais': 'Nome País Destinatário',
  'nfeProc.NFe.infNFe.dest.indIEDest': 'Indicador IE Destinatário',
  'nfeProc.NFe.infNFe.dest.xNome': 'Nome Destinatário',
  'nfeProc.NFe.infNFe.det.@nItem': 'Item',
  // COFINS
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSAliq.CST': 'CST COFINS Alíquota',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSAliq.pCOFINS': '% COFINS Alíquota',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSAliq.vBC': 'Base COFINS Alíquota',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSAliq.vCOFINS': 'Valor COFINS Alíquota',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSNT.CST': 'CST COFINS NT',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSOutr.CST': 'CST COFINS Outras',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSOutr.pCOFINS': '% COFINS Outras',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSOutr.vBC': 'Base COFINS Outras',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSOutr.vCOFINS': 'Valor COFINS Outras',
  // ICMS
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.CST': 'CST ICMS 00',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.modBC': 'Modalidade BC ICMS',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.orig': 'Origem Mercadoria ICMS',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.pICMS': '% ICMS',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.vBC': 'Base ICMS',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.vICMS': 'Valor ICMS',
  // ICMS ST (Adicional)
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMSST.pST': '% ICMS ST',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMSST.vBCST': 'Base ICMS ST',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMSST.vICMSST': 'Valor ICMS ST',
  // IPI
  'nfeProc.NFe.infNFe.det.imposto.IPI.IPINT.CST': 'CST IPI NT',
  'nfeProc.NFe.infNFe.det.imposto.IPI.cEnq': 'Código Enquadramento IPI',
  // PIS
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISAliq.CST': 'CST PIS Alíquota',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISAliq.pPIS': '% PIS Alíquota',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISAliq.vBC': 'Base PIS Alíquota',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISAliq.vPIS': 'Valor PIS Alíquota',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISNT.CST': 'CST PIS NT',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISOutr.CST': 'CST PIS Outras',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISOutr.pPIS': '% PIS Outras',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISOutr.vBC': 'Base PIS Outras',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISOutr.vPIS': 'Valor PIS Outras',
  // Produto
  'nfeProc.NFe.infNFe.det.infAdProd': 'Info Adicional Produto',
  'nfeProc.NFe.infNFe.det.prod.CFOP': 'CFOP',
  'nfeProc.NFe.infNFe.det.prod.NCM': 'NCM',
  'nfeProc.NFe.infNFe.det.prod.cEAN': 'EAN',
  'nfeProc.NFe.infNFe.det.prod.cEANTrib': 'EAN Trib.',
  'nfeProc.NFe.infNFe.det.prod.cProd': 'Código do Produto',
  'nfeProc.NFe.infNFe.det.prod.indTot': 'Compõe Total NF',
  'nfeProc.NFe.infNFe.det.prod.nItemPed': 'Número do Pedido',
  'nfeProc.NFe.infNFe.det.prod.qCom': 'Quantidade Comercial',
  'nfeProc.NFe.infNFe.det.prod.qTrib': 'Quantidade Tributária',
  'nfeProc.NFe.infNFe.det.prod.rastro.dFab': 'Data Fabricação',
  'nfeProc.NFe.infNFe.det.prod.rastro.dVal': 'Data Validade',
  'nfeProc.NFe.infNFe.det.prod.rastro.nLote': 'Número do Lote',
  'nfeProc.NFe.infNFe.det.prod.rastro.qLote': 'Quantidade Itens Lote',
  'nfeProc.NFe.infNFe.det.prod.uCom': 'Unidade Comercial',
  'nfeProc.NFe.infNFe.det.prod.uTrib': 'Unidade Tributária',
  'nfeProc.NFe.infNFe.det.prod.vProd': 'Valor do Produto',
  'nfeProc.NFe.infNFe.det.prod.vUnCom': 'Valor Unitário Comercial',
  'nfeProc.NFe.infNFe.det.prod.vUnTrib': 'Valor Unitário Tributário',
  'nfeProc.NFe.infNFe.det.prod.xPed': 'Pedido',
  'nfeProc.NFe.infNFe.det.prod.xProd': 'Descrição do Produto',
  'nfeProc.NFe.infNFe.det.prod.nFCI': 'Número da Ficha de Conteúdo de Importação (FCI)',
  'nfeProc.NFe.infNFe.det.prod.vDesc': 'Valor do Desconto do Produto',
  'nfeProc.NFe.infNFe.det.prod.vFrete': 'Valor do Frete do Produto',
  // Emissor
  'nfeProc.NFe.infNFe.emit.CNPJ': 'CNPJ do Emitente',
  'nfeProc.NFe.infNFe.emit.CRT': 'Regime Tributário',
  'nfeProc.NFe.infNFe.emit.IE': 'IE do Emitente',
  'nfeProc.NFe.infNFe.emit.enderEmit.CEP': 'CEP do Emitente',
  'nfeProc.NFe.infNFe.emit.enderEmit.UF': 'UF do Emitente',
  'nfeProc.NFe.infNFe.emit.enderEmit.cMun': 'Município do Emitente',
  'nfeProc.NFe.infNFe.emit.enderEmit.cPais': 'País do Emitente Codigo',
  'nfeProc.NFe.infNFe.emit.enderEmit.fone': 'Telefone do Emitente',
  'nfeProc.NFe.infNFe.emit.enderEmit.nro': 'Número do Emitente',
  'nfeProc.NFe.infNFe.emit.enderEmit.xBairro': 'Bairro do Emitente',
  'nfeProc.NFe.infNFe.emit.enderEmit.xLgr': 'Logradouro do Emitente',
  'nfeProc.NFe.infNFe.emit.enderEmit.xMun': 'Cidade do Emitente',
  'nfeProc.NFe.infNFe.emit.enderEmit.xPais': 'País do Emitente',
  'nfeProc.NFe.infNFe.emit.xFant': 'Nome Fantasia',
  'nfeProc.NFe.infNFe.emit.xNome': 'Razão Social',
  // Entrega
  'nfeProc.NFe.infNFe.entrega.CNPJ': 'CNPJ Entrega',
  'nfeProc.NFe.infNFe.entrega.UF': 'UF Entrega',
  'nfeProc.NFe.infNFe.entrega.cMun': 'Município Entrega',
  'nfeProc.NFe.infNFe.entrega.nro': 'Número Entrega',
  'nfeProc.NFe.infNFe.entrega.xBairro': 'Bairro Entrega',
  'nfeProc.NFe.infNFe.entrega.xCpl': 'Complemento Entrega',
  'nfeProc.NFe.infNFe.entrega.xLgr': 'Logradouro Entrega',
  'nfeProc.NFe.infNFe.entrega.xMun': 'Cidade Entrega',
  // Identificação
  'nfeProc.NFe.infNFe.ide.NFref.refNFe': 'NF-e Referenciada',
  'nfeProc.NFe.infNFe.ide.cDV': 'Dígito Verificador',
  'nfeProc.NFe.infNFe.ide.cMunFG': 'Município de Ocorrência',
  'nfeProc.NFe.infNFe.ide.cNF': 'Código NF-e',
  'nfeProc.NFe.infNFe.ide.cUF': 'UF NF-e',
  'nfeProc.NFe.infNFe.ide.dhEmi': 'Data/Hora Emissão',
  'nfeProc.NFe.infNFe.ide.dhSaiEnt': 'Data/Hora Saída/Entrada',
  'nfeProc.NFe.infNFe.ide.finNFe': 'Finalidade NF-e',
  'nfeProc.NFe.infNFe.ide.idDest': 'Identificação Destino',
  'nfeProc.NFe.infNFe.ide.indFinal': 'Consumidor Final',
  'nfeProc.NFe.infNFe.ide.indPres': 'Indicador de Presença',
  'nfeProc.NFe.infNFe.ide.mod': 'Modelo NF-e',
  'nfeProc.NFe.infNFe.ide.nNF': 'Número NF-e',
  'nfeProc.NFe.infNFe.ide.natOp': 'Natureza da Operação',
  'nfeProc.NFe.infNFe.ide.procEmi': 'Processo de Emissão',
  'nfeProc.NFe.infNFe.ide.serie': 'Série',
  'nfeProc.NFe.infNFe.ide.tpAmb': 'Ambiente',
  'nfeProc.NFe.infNFe.ide.tpEmis': 'Tipo de Emissão',
  'nfeProc.NFe.infNFe.ide.tpImp': 'Formato de Impressão',
  'nfeProc.NFe.infNFe.ide.tpNF': 'Tipo NF-e',
  'nfeProc.NFe.infNFe.ide.verProc': 'Versão do Processo 2',
  'nfeProc.NFe.infNFe.infAdic.infCpl': 'Informação Complementar',
  // Pagamento
  'nfeProc.NFe.infNFe.pag.detPag.tPag': 'Tipo de Pagamento',
  'nfeProc.NFe.infNFe.pag.detPag.vPag': 'Valor Pago',
  // Totais
  'nfeProc.NFe.infNFe.total.ICMSTot.vBC': 'Base ICMS Total',
  'nfeProc.NFe.infNFe.total.ICMSTot.vBCST': 'Base ST Total',
  'nfeProc.NFe.infNFe.total.ICMSTot.vCOFINS': 'COFINS Total',
  'nfeProc.NFe.infNFe.total.ICMSTot.vDesc': 'Desconto Total',
  'nfeProc.NFe.infNFe.total.ICMSTot.vFCP': 'FCP Total',
  'nfeProc.NFe.infNFe.total.ICMSTot.vFCPST': 'FCP ST Total',
  'nfeProc.NFe.infNFe.total.ICMSTot.vFCPSTRet': 'FCP ST Ret Total',
  'nfeProc.NFe.infNFe.total.ICMSTot.vFrete': 'Frete Total',
  'nfeProc.NFe.infNFe.total.ICMSTot.vICMS': 'ICMS Total',
  'nfeProc.NFe.infNFe.total.ICMSTot.vICMSDeson': 'ICMS Deson Total',
  'nfeProc.NFe.infNFe.total.ICMSTot.vII': 'II Total',
  'nfeProc.NFe.infNFe.total.ICMSTot.vIPI': 'IPI Total',
  'nfeProc.NFe.infNFe.total.ICMSTot.vIPIDevol': 'IPI Devolução Total',
  'nfeProc.NFe.infNFe.total.ICMSTot.vNF': 'Valor NF-e',
  'nfeProc.NFe.infNFe.total.ICMSTot.vOutro': 'Outros Totais',
  'nfeProc.NFe.infNFe.total.ICMSTot.vPIS': 'PIS Total',
  'nfeProc.NFe.infNFe.total.ICMSTot.vProd': 'Produtos Total',
  'nfeProc.NFe.infNFe.total.ICMSTot.vST': 'ST Total',
  'nfeProc.NFe.infNFe.total.ICMSTot.vSeg': 'Seguro Total',
  // Transporte
  'nfeProc.NFe.infNFe.transp.modFrete': 'Modalidade Frete',
  'nfeProc.NFe.infNFe.transp.transporta.CNPJ': 'CNPJ Transportadora',
  'nfeProc.NFe.infNFe.transp.transporta.IE': 'IE Transportadora',
  'nfeProc.NFe.infNFe.transp.transporta.UF': 'UF Transportadora',
  'nfeProc.NFe.infNFe.transp.transporta.xEnder': 'Endereço Transportadora',
  'nfeProc.NFe.infNFe.transp.transporta.xMun': 'Município Transportadora',
  'nfeProc.NFe.infNFe.transp.transporta.xNome': 'Nome Transportadora',
  'nfeProc.NFe.infNFe.transp.vol.pesoB': 'Peso Bruto',
  'nfeProc.NFe.infNFe.transp.vol.pesoL': 'Peso Líquido',
  'nfeProc.NFe.infNFe.transp.vol.qVol': 'Quantidade Volumes',
  // Protocolo
  'nfeProc.protNFe.@versao': 'Versão Protocolo',
  'nfeProc.protNFe.infProt.cStat': 'Status Protocolo',
  'nfeProc.protNFe.infProt.chNFe': 'Chave NF-e',
  'nfeProc.protNFe.infProt.dhRecbto': 'Data Recebimento',
  'nfeProc.protNFe.infProt.digVal': 'Digest Valor Protocolo',
  'nfeProc.protNFe.infProt.nProt': 'Número Protocolo',
  'nfeProc.protNFe.infProt.tpAmb': 'Ambiente Protocolo',
  'nfeProc.protNFe.infProt.verAplic': 'Versão App Protocolo',
  'nfeProc.protNFe.infProt.xMotivo': 'Motivo Autorização',
  // Otros que faltaron
  'nfeProc.NFe.infNFe.det.imposto.ICMSUFDest.pICMSInter': 'Percentual interestadual para cálculo do ICMS a partilhar entre os estados',
  'nfeProc.NFe.infNFe.det.imposto.ICMSUFDest.pICMSInterPart': 'Percentual de partilha do ICMS entre origem e destino',
  'nfeProc.NFe.infNFe.det.imposto.ICMSUFDest.pICMSUFDest': 'Alíquota interna do ICMS na UF do destinatário',
  'nfeProc.NFe.infNFe.det.imposto.ICMSUFDest.vBCUFDest': 'Base de cálculo do ICMS na UF do destinatário',
  'nfeProc.NFe.infNFe.det.imposto.ICMSUFDest.vBCFCPUFDest': 'Base de cálculo do FCP na UF do destinatário',
  'nfeProc.NFe.infNFe.det.imposto.ICMSUFDest.vICMSUFDest': 'Valor do ICMS partilhado para a UF do destinatário',
  'nfeProc.NFe.infNFe.det.imposto.ICMSUFDest.vICMSUFRemet': 'Valor do ICMS partilhado para a UF do remetente'
};

export const CAMPOS_MONEDA = [
  // Cobranza
  'nfeProc.NFe.infNFe.cobr.dup.vDup',
  'nfeProc.NFe.infNFe.cobr.fat.vDesc',
  'nfeProc.NFe.infNFe.cobr.fat.vLiq',
  'nfeProc.NFe.infNFe.cobr.fat.vOrig',
  // COFINS
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSAliq.pCOFINS',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSAliq.vBC',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSAliq.vCOFINS',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSOutr.pCOFINS',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSOutr.vBC',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSOutr.vCOFINS',
  // ICMS (item)
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.pICMS',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.vBC',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.vICMS',
  // ICMS ST (Adicional)
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMSST.pST',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMSST.vBCST',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMSST.vICMSST',
  // PIS
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISAliq.pPIS',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISAliq.vBC',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISAliq.vPIS',
  // Productos (cantidades y valores unitarios)
  'nfeProc.NFe.infNFe.det.prod.qCom',
  'nfeProc.NFe.infNFe.det.prod.qTrib',
  'nfeProc.NFe.infNFe.det.prod.rastro.qLote',
  'nfeProc.NFe.infNFe.det.prod.vProd',
  'nfeProc.NFe.infNFe.det.prod.vUnCom',
  'nfeProc.NFe.infNFe.det.prod.vUnTrib',
  'nfeProc.NFe.infNFe.det.prod.vDesc',
  'nfeProc.NFe.infNFe.det.prod.vFrete',
  // Pago
  'nfeProc.NFe.infNFe.pag.detPag.vPag',
  // Totales generales
  'nfeProc.NFe.infNFe.total.ICMSTot.vBC',
  'nfeProc.NFe.infNFe.total.ICMSTot.vBCST',
  'nfeProc.NFe.infNFe.total.ICMSTot.vCOFINS',
  'nfeProc.NFe.infNFe.total.ICMSTot.vDesc',
  'nfeProc.NFe.infNFe.total.ICMSTot.vFCP',
  'nfeProc.NFe.infNFe.total.ICMSTot.vFCPST',
  'nfeProc.NFe.infNFe.total.ICMSTot.vFCPSTRet',
  'nfeProc.NFe.infNFe.total.ICMSTot.vFrete',
  'nfeProc.NFe.infNFe.total.ICMSTot.vICMS',
  'nfeProc.NFe.infNFe.total.ICMSTot.vICMSDeson',
  'nfeProc.NFe.infNFe.total.ICMSTot.vII',
  'nfeProc.NFe.infNFe.total.ICMSTot.vIPI',
  'nfeProc.NFe.infNFe.total.ICMSTot.vIPIDevol',
  'nfeProc.NFe.infNFe.total.ICMSTot.vNF',
  'nfeProc.NFe.infNFe.total.ICMSTot.vOutro',
  'nfeProc.NFe.infNFe.total.ICMSTot.vPIS',
  'nfeProc.NFe.infNFe.total.ICMSTot.vProd',
  'nfeProc.NFe.infNFe.total.ICMSTot.vST',
  'nfeProc.NFe.infNFe.total.ICMSTot.vSeg',
  // Transporte (volúmenes y pesos)
  'nfeProc.NFe.infNFe.transp.vol.pesoB',
  'nfeProc.NFe.infNFe.transp.vol.pesoL',
  'nfeProc.NFe.infNFe.transp.vol.qVol'
];
