export const DICCIONARIO_CV = {
  // Campos principales en el orden especificado
  'nfeProc.NFe.infNFe.ide.natOp': 'Natureza Operação',
  'nfeProc.NFe.infNFe.ide.nNF': 'NFe',
  'nfeProc.NFe.infNFe.ide.dhEmi': 'Data',
  'nfeProc.NFe.infNFe.ide.tpNF': 'Tipo Operação',
  'nfeProc.NFe.infNFe.ide.idDest': 'Tipo Destino',
  'nfeProc.NFe.infNFe.ide.finNFe': 'Finalidade',
  'nfeProc.NFe.infNFe.ide.indFinal': 'Consumidor Final',
  'nfeProc.NFe.infNFe.emit.CNPJ': 'CNPJ Emitente',
  'nfeProc.NFe.infNFe.emit.xNome': 'Empresa Emitente',
  'nfeProc.NFe.infNFe.emit.xFant': 'Empresa Emitente Fantasia',
  'nfeProc.NFe.infNFe.emit.enderEmit.xLgr': 'Rua Emitente',
  'nfeProc.NFe.infNFe.emit.enderEmit.nro': 'Número Emitente',
  'nfeProc.NFe.infNFe.emit.enderEmit.xBairro': 'Bairro Emitente',
  'nfeProc.NFe.infNFe.emit.enderEmit.xMun': 'Município Emitente',
  'nfeProc.NFe.infNFe.emit.enderEmit.UF': 'Estado Emitente',
  'nfeProc.NFe.infNFe.emit.enderEmit.CEP': 'CEP Emitente',
  'nfeProc.NFe.infNFe.emit.enderEmit.xPais': 'País Emitente',
  'nfeProc.NFe.infNFe.emit.enderEmit.fone': 'Telefone Emitente',
  'nfeProc.NFe.infNFe.emit.IE': 'Inscrição Estadual Emitente',
  'nfeProc.NFe.infNFe.emit.CRT': 'Código Regime tributário Emitente',
  'nfeProc.NFe.infNFe.dest.CNPJ': 'CNPJ Destinatário',
  'nfeProc.NFe.infNFe.dest.xNome': 'Nome Destinatário',
  'nfeProc.NFe.infNFe.dest.enderDest.xLgr': 'Rua Destinatário',
  'nfeProc.NFe.infNFe.dest.enderDest.nro': 'Número Destinatário',
  'nfeProc.NFe.infNFe.dest.enderDest.xBairro': 'Bairro Destinatário',
  'nfeProc.NFe.infNFe.dest.enderDest.xMun': 'Município Destinatário',
  'nfeProc.NFe.infNFe.dest.enderDest.UF': 'Estado Destinatário',
  'nfeProc.NFe.infNFe.dest.enderDest.CEP': 'CEP Destinatário',
  'nfeProc.NFe.infNFe.dest.enderDest.xPais': 'País Destinatário',
  'nfeProc.NFe.infNFe.dest.enderDest.fone': 'Telefone Destinatário',
  'nfeProc.NFe.infNFe.dest.indIEDest': 'Contribuinte de ICMS',
  'nfeProc.NFe.infNFe.dest.IE': 'Inscrição Estadual Destinatário',
  'nfeProc.NFe.infNFe.dest.email': 'E-mail Destinatário',
  'nfeProc.NFe.infNFe.entrega.CNPJ': 'CNPJ Entrega',
  'nfeProc.NFe.infNFe.entrega.xLgr': 'Rua Entrega',
  'nfeProc.NFe.infNFe.entrega.nro': 'Número Entrega',
  'nfeProc.NFe.infNFe.entrega.xBairro': 'Bairro Entrega',
  'nfeProc.NFe.infNFe.entrega.xMun': 'Município Entrega',
  'nfeProc.NFe.infNFe.entrega.UF': 'Estado Entrega',
  'nfeProc.NFe.infNFe.det.prod.cProd': 'Código Produto',
  'nfeProc.NFe.infNFe.det.prod.cEAN': 'CEAN',
  'nfeProc.NFe.infNFe.det.prod.xProd': 'Nome Produto',
  'nfeProc.NFe.infNFe.det.prod.NCM': 'Nomenclatura Comum MERCOSUL',
  'nfeProc.NFe.infNFe.det.prod.CFOP': 'CFOP',
  'nfeProc.NFe.infNFe.det.prod.uCom': 'Unidade Comercial',
  'nfeProc.NFe.infNFe.det.prod.qCom': 'Quantidade',
  'nfeProc.NFe.infNFe.det.prod.vUnCom': 'Valor Unitário',
  'nfeProc.NFe.infNFe.det.prod.vProd': 'Valor Produtos',
  'nfeProc.NFe.infNFe.det.prod.indTot': 'Compõe Total Nota Fiscal',
  'nfeProc.NFe.infNFe.det.prod.rastro.nLote': 'Número Lote',
  'nfeProc.NFe.infNFe.det.prod.rastro.qLote': 'Quantidade Itens Lote',
  'nfeProc.NFe.infNFe.det.prod.rastro.dFab': 'Data Fabricação',
  'nfeProc.NFe.infNFe.det.prod.rastro.dVal': 'Data Validade',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.orig': 'Origem Mercadoria',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.CST': 'ICMS CST',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.modBC': 'modalidade de determinação da base de cálculo do ICMS.',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.vBC': 'Base Cálculo ICMS',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.pICMS': 'Percentual ICMS',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.vICMS': 'Valor ICMS',
  'nfeProc.NFe.infNFe.det.imposto.IPI.cEnq': 'Código Enquadramento IPI',
  'nfeProc.NFe.infNFe.det.imposto.IPI.IPINT.CST': 'IPI CST',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISAliq.CST': 'NFe.infNFe.det.imposto.PIS.PISAliq.CST',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISAliq.vBC': 'NFe.infNFe.det.imposto.PIS.PISAliq.vBC',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISAliq.pPIS': 'NFe.infNFe.det.imposto.PIS.PISAliq.pPIS',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISAliq.vPIS': 'NFe.infNFe.det.imposto.PIS.PISAliq.vPIS',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSAliq.CST': 'NFe.infNFe.det.imposto.COFINS.COFINSAliq.CST',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSAliq.vBC': 'NFe.infNFe.det.imposto.COFINS.COFINSAliq.vBC',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSAliq.pCOFINS': 'NFe.infNFe.det.imposto.COFINS.COFINSAliq.pCOFINS',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSAliq.vCOFINS': 'NFe.infNFe.det.imposto.COFINS.COFINSAliq.vCOFINS',
  'nfeProc.NFe.infNFe.det.infAdProd': 'NFe.infNFe.det.infAdProd',
  'nfeProc.NFe.infNFe.det.@nItem': 'NFe.infNFe.det.Attribute:nItem',
  'nfeProc.NFe.infNFe.total.ICMSTot.vBC': 'NFe.infNFe.total.ICMSTot.vBC',
  'nfeProc.NFe.infNFe.total.ICMSTot.vICMS': 'NFe.infNFe.total.ICMSTot.vICMS',
  'nfeProc.NFe.infNFe.total.ICMSTot.vICMSDeson': 'NFe.infNFe.total.ICMSTot.vICMSDeson',
  'nfeProc.NFe.infNFe.total.ICMSTot.vFCP': 'NFe.infNFe.total.ICMSTot.vFCP',
  'nfeProc.NFe.infNFe.total.ICMSTot.vBCST': 'NFe.infNFe.total.ICMSTot.vBCST',
  'nfeProc.NFe.infNFe.total.ICMSTot.vST': 'NFe.infNFe.total.ICMSTot.vST',
  'nfeProc.NFe.infNFe.total.ICMSTot.vFCPST': 'NFe.infNFe.total.ICMSTot.vFCPST',
  'nfeProc.NFe.infNFe.total.ICMSTot.vFCPSTRet': 'NFe.infNFe.total.ICMSTot.vFCPSTRet',
  'nfeProc.NFe.infNFe.total.ICMSTot.vProd': 'NFe.infNFe.total.ICMSTot.vProd',
  'nfeProc.NFe.infNFe.total.ICMSTot.vFrete': 'NFe.infNFe.total.ICMSTot.vFrete',
  'nfeProc.NFe.infNFe.total.ICMSTot.vSeg': 'NFe.infNFe.total.ICMSTot.vSeg',
  'nfeProc.NFe.infNFe.total.ICMSTot.vDesc': 'NFe.infNFe.total.ICMSTot.vDesc',
  'nfeProc.NFe.infNFe.total.ICMSTot.vII': 'NFe.infNFe.total.ICMSTot.vII',
  'nfeProc.NFe.infNFe.total.ICMSTot.vIPI': 'NFe.infNFe.total.ICMSTot.vIPI',
  'nfeProc.NFe.infNFe.total.ICMSTot.vIPIDevol': 'NFe.infNFe.total.ICMSTot.vIPIDevol',
  'nfeProc.NFe.infNFe.total.ICMSTot.vPIS': 'NFe.infNFe.total.ICMSTot.vPIS',
  'nfeProc.NFe.infNFe.total.ICMSTot.vCOFINS': 'NFe.infNFe.total.ICMSTot.vCOFINS',
  'nfeProc.NFe.infNFe.total.ICMSTot.vOutro': 'NFe.infNFe.total.ICMSTot.vOutro',
  'nfeProc.NFe.infNFe.total.ICMSTot.vNF': 'NFe.infNFe.total.ICMSTot.vNF',
  'nfeProc.NFe.infNFe.transp.modFrete': 'NFe.infNFe.transp.modFrete',
  'nfeProc.NFe.infNFe.transp.transporta.CNPJ': 'NFe.infNFe.transp.transporta.CNPJ',
  'nfeProc.NFe.infNFe.transp.transporta.xNome': 'NFe.infNFe.transp.transporta.xNome',
  'nfeProc.NFe.infNFe.transp.transporta.IE': 'NFe.infNFe.transp.transporta.IE',
  'nfeProc.NFe.infNFe.transp.transporta.xEnder': 'NFe.infNFe.transp.transporta.xEnder',
  'nfeProc.NFe.infNFe.transp.transporta.xMun': 'NFe.infNFe.transp.transporta.xMun',
  'nfeProc.NFe.infNFe.transp.transporta.UF': 'NFe.infNFe.transp.transporta.UF',
  'nfeProc.NFe.infNFe.transp.vol.qVol': 'NFe.infNFe.transp.vol.qVol',
  'nfeProc.NFe.infNFe.transp.vol.pesoL': 'NFe.infNFe.transp.vol.pesoL',
  'nfeProc.NFe.infNFe.transp.vol.pesoB': 'NFe.infNFe.transp.vol.pesoB',
  'nfeProc.NFe.infNFe.cobr.fat.nFat': 'NFe.infNFe.cobr.fat.nFat',
  'nfeProc.NFe.infNFe.cobr.fat.vOrig': 'NFe.infNFe.cobr.fat.vOrig',
  'nfeProc.NFe.infNFe.cobr.fat.vDesc': 'NFe.infNFe.cobr.fat.vDesc',
  'nfeProc.NFe.infNFe.cobr.fat.vLiq': 'NFe.infNFe.cobr.fat.vLiq',
  'nfeProc.NFe.infNFe.cobr.dup.nDup': 'NFe.infNFe.cobr.dup.nDup',
  'nfeProc.NFe.infNFe.cobr.dup.dVenc': 'NFe.infNFe.cobr.dup.dVenc',
  'nfeProc.NFe.infNFe.cobr.dup.vDup': 'NFe.infNFe.cobr.dup.vDup',
  'nfeProc.NFe.infNFe.pag.detPag.tPag': 'NFe.infNFe.pag.detPag.tPag',
  'nfeProc.NFe.infNFe.pag.detPag.vPag': 'NFe.infNFe.pag.detPag.vPag',
  'nfeProc.NFe.infNFe.det.prod.nItemPed': 'Número Pedido',
  'nfeProc.NFe.infNFe.det.prod.xPed': 'Código Cliente',
  'nfeProc.NFe.infNFe.infAdic.infCpl': 'NFe.infNFe.infAdic.infCpl.5',
  
  // Campos adicionales para compatibilidad
  'nfeProc.@versao': 'Versão do Processo',
  'nfeProc.NFe.Signature.KeyInfo.X509Data.X509Certificate': 'Certificado X509',
  'nfeProc.NFe.Signature.SignatureValue': 'Valor da Assinatura',
  'nfeProc.NFe.Signature.SignedInfo.CanonicalizationMethod.@Algorithm': 'Algoritmo de Canonicalização',
  'nfeProc.NFe.Signature.SignedInfo.Reference.@URI': 'URI da Referência',
  'nfeProc.NFe.Signature.SignedInfo.Reference.DigestMethod.@Algorithm': 'Algoritmo de Digestão',
  'nfeProc.NFe.Signature.SignedInfo.Reference.DigestValue': 'Valor de Digestão',
  'nfeProc.NFe.Signature.SignedInfo.Reference.Transforms.Transform.@Algorithm': 'Algoritmo de Transformação',
  'nfeProc.NFe.Signature.SignedInfo.SignatureMethod.@Algorithm': 'Método de Assinatura',
  'nfeProc.NFe.infNFe.@Id': 'ID da NF-e',
  'nfeProc.NFe.infNFe.@versao': 'Versão da NF-e',
  // COFINS
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSNT.CST': 'CST COFINS NT',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSOutr.CST': 'CST COFINS Outras',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSOutr.pCOFINS': '% COFINS Outras',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSOutr.vBC': 'Base COFINS Outras',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSOutr.vCOFINS': 'Valor COFINS Outras',
  // ICMS ST (Adicional)
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMSST.pST': '% ICMS ST',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMSST.vBCST': 'Base ICMS ST',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMSST.vICMSST': 'Valor ICMS ST',
  // PIS
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISNT.CST': 'CST PIS NT',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISOutr.CST': 'CST PIS Outras',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISOutr.pPIS': '% PIS Outras',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISOutr.vBC': 'Base PIS Outras',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISOutr.vPIS': 'Valor PIS Outras',
  // Produto
  'nfeProc.NFe.infNFe.det.prod.cEANTrib': 'EAN Trib.',
  'nfeProc.NFe.infNFe.det.prod.qTrib': 'Quantidade Tributária',
  'nfeProc.NFe.infNFe.det.prod.uTrib': 'Unidade Tributária',
  'nfeProc.NFe.infNFe.det.prod.vUnTrib': 'Valor Unitário Tributário',
  'nfeProc.NFe.infNFe.det.prod.nFCI': 'Número da Ficha de Conteúdo de Importação (FCI)',
  'nfeProc.NFe.infNFe.det.prod.vDesc': 'Valor do Desconto do Produto',
  'nfeProc.NFe.infNFe.det.prod.vFrete': 'Valor do Frete do Produto',
  // Emissor
  'nfeProc.NFe.infNFe.emit.enderEmit.cMun': 'Município do Emitente',
  'nfeProc.NFe.infNFe.emit.enderEmit.cPais': 'País do Emitente Codigo',
  // Entrega
  'nfeProc.NFe.infNFe.entrega.xCpl': 'Complemento Entrega',
  // Identificação
  'nfeProc.NFe.infNFe.ide.NFref.refNFe': 'NF-e Referenciada',
  'nfeProc.NFe.infNFe.ide.cDV': 'Dígito Verificador',
  'nfeProc.NFe.infNFe.ide.cMunFG': 'Município de Ocorrência',
  'nfeProc.NFe.infNFe.ide.cNF': 'Código NF-e',
  'nfeProc.NFe.infNFe.ide.cUF': 'UF NF-e',
  'nfeProc.NFe.infNFe.ide.dhSaiEnt': 'Data/Hora Saída/Entrada',
  'nfeProc.NFe.infNFe.ide.indPres': 'Indicador de Presença',
  'nfeProc.NFe.infNFe.ide.mod': 'Modelo NF-e',
  'nfeProc.NFe.infNFe.ide.procEmi': 'Processo de Emissão',
  'nfeProc.NFe.infNFe.ide.serie': 'Série',
  'nfeProc.NFe.infNFe.ide.tpAmb': 'Ambiente',
  'nfeProc.NFe.infNFe.ide.tpEmis': 'Tipo de Emissão',
  'nfeProc.NFe.infNFe.ide.tpImp': 'Formato de Impressão',
  'nfeProc.NFe.infNFe.ide.verProc': 'Versão do Processo 2',
  // Protocolo
  'nfeProc.protNFe.@versao': 'Versão Protocolo',
  'nfeProc.protNFe.infProt.cStat': 'Status Protocolo',
  'nfeProc.protNFe.infProt.chNFe': 'Chave NF-e',
  'nfeProc.protNFe.infProt.dhRecbto': 'Data Recebimento',
  'nfeProc.protNFe.infProt.digVal': 'Digest Valor Protocolo',
  'nfeProc.protNFe.infProt.nProt': 'Número Protocolo',
  'nfeProc.protNFe.infProt.tpAmb': 'Ambiente Protocolo',
  'nfeProc.protNFe.infProt.verAplic': 'Versão App Protocolo',
  'nfeProc.protNFe.infProt.xMotivo': 'Motivo Autorização',
  // Otros que faltaron
  'nfeProc.NFe.infNFe.det.imposto.ICMSUFDest.pICMSInter': 'Percentual interestadual para cálculo do ICMS a partilhar entre os estados',
  'nfeProc.NFe.infNFe.det.imposto.ICMSUFDest.pICMSInterPart': 'Percentual de partilha do ICMS entre origem e destino',
  'nfeProc.NFe.infNFe.det.imposto.ICMSUFDest.pICMSUFDest': 'Alíquota interna do ICMS na UF do destinatário',
  'nfeProc.NFe.infNFe.det.imposto.ICMSUFDest.vBCUFDest': 'Base de cálculo do ICMS na UF do destinatário',
  'nfeProc.NFe.infNFe.det.imposto.ICMSUFDest.vBCFCPUFDest': 'Base de cálculo do FCP na UF do destinatário',
  'nfeProc.NFe.infNFe.det.imposto.ICMSUFDest.vICMSUFDest': 'Valor do ICMS partilhado para a UF do destinatário',
  'nfeProc.NFe.infNFe.det.imposto.ICMSUFDest.vICMSUFRemet': 'Valor do ICMS partilhado para a UF do remetente'
};

// Orden por defecto de los campos según lo especificado
export const ORDEN_CAMPOS_POR_DEFECTO = [
  'nfeProc.NFe.infNFe.ide.natOp',
  'nfeProc.NFe.infNFe.ide.nNF',
  'nfeProc.NFe.infNFe.ide.dhEmi',
  'nfeProc.NFe.infNFe.ide.tpNF',
  'nfeProc.NFe.infNFe.ide.idDest',
  'nfeProc.NFe.infNFe.ide.finNFe',
  'nfeProc.NFe.infNFe.ide.indFinal',
  'nfeProc.NFe.infNFe.emit.CNPJ',
  'nfeProc.NFe.infNFe.emit.xNome',
  'nfeProc.NFe.infNFe.emit.xFant',
  'nfeProc.NFe.infNFe.emit.enderEmit.xLgr',
  'nfeProc.NFe.infNFe.emit.enderEmit.nro',
  'nfeProc.NFe.infNFe.emit.enderEmit.xBairro',
  'nfeProc.NFe.infNFe.emit.enderEmit.xMun',
  'nfeProc.NFe.infNFe.emit.enderEmit.UF',
  'nfeProc.NFe.infNFe.emit.enderEmit.CEP',
  'nfeProc.NFe.infNFe.emit.enderEmit.xPais',
  'nfeProc.NFe.infNFe.emit.enderEmit.fone',
  'nfeProc.NFe.infNFe.emit.IE',
  'nfeProc.NFe.infNFe.emit.CRT',
  'nfeProc.NFe.infNFe.dest.CNPJ',
  'nfeProc.NFe.infNFe.dest.xNome',
  'nfeProc.NFe.infNFe.dest.enderDest.xLgr',
  'nfeProc.NFe.infNFe.dest.enderDest.nro',
  'nfeProc.NFe.infNFe.dest.enderDest.xBairro',
  'nfeProc.NFe.infNFe.dest.enderDest.xMun',
  'nfeProc.NFe.infNFe.dest.enderDest.UF',
  'nfeProc.NFe.infNFe.dest.enderDest.CEP',
  'nfeProc.NFe.infNFe.dest.enderDest.xPais',
  'nfeProc.NFe.infNFe.dest.enderDest.fone',
  'nfeProc.NFe.infNFe.dest.indIEDest',
  'nfeProc.NFe.infNFe.dest.IE',
  'nfeProc.NFe.infNFe.dest.email',
  'nfeProc.NFe.infNFe.entrega.CNPJ',
  'nfeProc.NFe.infNFe.entrega.xLgr',
  'nfeProc.NFe.infNFe.entrega.nro',
  'nfeProc.NFe.infNFe.entrega.xBairro',
  'nfeProc.NFe.infNFe.entrega.xMun',
  'nfeProc.NFe.infNFe.entrega.UF',
  'nfeProc.NFe.infNFe.det.prod.cProd',
  'nfeProc.NFe.infNFe.det.prod.cEAN',
  'nfeProc.NFe.infNFe.det.prod.xProd',
  'nfeProc.NFe.infNFe.det.prod.NCM',
  'nfeProc.NFe.infNFe.det.prod.CFOP',
  'nfeProc.NFe.infNFe.det.prod.uCom',
  'nfeProc.NFe.infNFe.det.prod.qCom',
  'nfeProc.NFe.infNFe.det.prod.vUnCom',
  'nfeProc.NFe.infNFe.det.prod.vProd',
  'nfeProc.NFe.infNFe.det.prod.indTot',
  'nfeProc.NFe.infNFe.det.prod.rastro.nLote',
  'nfeProc.NFe.infNFe.det.prod.rastro.qLote',
  'nfeProc.NFe.infNFe.det.prod.rastro.dFab',
  'nfeProc.NFe.infNFe.det.prod.rastro.dVal',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.orig',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.CST',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.modBC',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.vBC',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.pICMS',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.vICMS',
  'nfeProc.NFe.infNFe.det.imposto.IPI.cEnq',
  'nfeProc.NFe.infNFe.det.imposto.IPI.IPINT.CST',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISAliq.CST',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISAliq.vBC',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISAliq.pPIS',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISAliq.vPIS',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSAliq.CST',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSAliq.vBC',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSAliq.pCOFINS',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSAliq.vCOFINS',
  'nfeProc.NFe.infNFe.det.infAdProd',
  'nfeProc.NFe.infNFe.det.@nItem',
  'nfeProc.NFe.infNFe.total.ICMSTot.vBC',
  'nfeProc.NFe.infNFe.total.ICMSTot.vICMS',
  'nfeProc.NFe.infNFe.total.ICMSTot.vICMSDeson',
  'nfeProc.NFe.infNFe.total.ICMSTot.vFCP',
  'nfeProc.NFe.infNFe.total.ICMSTot.vBCST',
  'nfeProc.NFe.infNFe.total.ICMSTot.vST',
  'nfeProc.NFe.infNFe.total.ICMSTot.vFCPST',
  'nfeProc.NFe.infNFe.total.ICMSTot.vFCPSTRet',
  'nfeProc.NFe.infNFe.total.ICMSTot.vProd',
  'nfeProc.NFe.infNFe.total.ICMSTot.vFrete',
  'nfeProc.NFe.infNFe.total.ICMSTot.vSeg',
  'nfeProc.NFe.infNFe.total.ICMSTot.vDesc',
  'nfeProc.NFe.infNFe.total.ICMSTot.vII',
  'nfeProc.NFe.infNFe.total.ICMSTot.vIPI',
  'nfeProc.NFe.infNFe.total.ICMSTot.vIPIDevol',
  'nfeProc.NFe.infNFe.total.ICMSTot.vPIS',
  'nfeProc.NFe.infNFe.total.ICMSTot.vCOFINS',
  'nfeProc.NFe.infNFe.total.ICMSTot.vOutro',
  'nfeProc.NFe.infNFe.total.ICMSTot.vNF',
  'nfeProc.NFe.infNFe.transp.modFrete',
  'nfeProc.NFe.infNFe.transp.transporta.CNPJ',
  'nfeProc.NFe.infNFe.transp.transporta.xNome',
  'nfeProc.NFe.infNFe.transp.transporta.IE',
  'nfeProc.NFe.infNFe.transp.transporta.xEnder',
  'nfeProc.NFe.infNFe.transp.transporta.xMun',
  'nfeProc.NFe.infNFe.transp.transporta.UF',
  'nfeProc.NFe.infNFe.transp.vol.qVol',
  'nfeProc.NFe.infNFe.transp.vol.pesoL',
  'nfeProc.NFe.infNFe.transp.vol.pesoB',
  'nfeProc.NFe.infNFe.cobr.fat.nFat',
  'nfeProc.NFe.infNFe.cobr.fat.vOrig',
  'nfeProc.NFe.infNFe.cobr.fat.vDesc',
  'nfeProc.NFe.infNFe.cobr.fat.vLiq',
  'nfeProc.NFe.infNFe.cobr.dup.nDup',
  'nfeProc.NFe.infNFe.cobr.dup.dVenc',
  'nfeProc.NFe.infNFe.cobr.dup.vDup',
  'nfeProc.NFe.infNFe.pag.detPag.tPag',
  'nfeProc.NFe.infNFe.pag.detPag.vPag',
  'nfeProc.NFe.infNFe.infAdic.infCpl'
];

export const CAMPOS_MONEDA = [
  // Cobranza
  'nfeProc.NFe.infNFe.cobr.dup.vDup',
  'nfeProc.NFe.infNFe.cobr.fat.vOrig',
  'nfeProc.NFe.infNFe.cobr.fat.vDesc',
  'nfeProc.NFe.infNFe.cobr.fat.vLiq',
  
  // Productos
  'nfeProc.NFe.infNFe.det.prod.vProd',
  'nfeProc.NFe.infNFe.det.prod.vUnCom',
  'nfeProc.NFe.infNFe.det.prod.vUnTrib',
  'nfeProc.NFe.infNFe.det.prod.vDesc',
  'nfeProc.NFe.infNFe.det.prod.vFrete',
  
  // Impostos
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.vBC',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMS00.vICMS',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMSST.vBCST',
  'nfeProc.NFe.infNFe.det.imposto.ICMS.ICMSST.vICMSST',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISAliq.vBC',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISAliq.vPIS',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISOutr.vBC',
  'nfeProc.NFe.infNFe.det.imposto.PIS.PISOutr.vPIS',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSAliq.vBC',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSAliq.vCOFINS',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSOutr.vBC',
  'nfeProc.NFe.infNFe.det.imposto.COFINS.COFINSOutr.vCOFINS',
  
  // Totales
  'nfeProc.NFe.infNFe.total.ICMSTot.vBC',
  'nfeProc.NFe.infNFe.total.ICMSTot.vICMS',
  'nfeProc.NFe.infNFe.total.ICMSTot.vICMSDeson',
  'nfeProc.NFe.infNFe.total.ICMSTot.vFCP',
  'nfeProc.NFe.infNFe.total.ICMSTot.vBCST',
  'nfeProc.NFe.infNFe.total.ICMSTot.vST',
  'nfeProc.NFe.infNFe.total.ICMSTot.vFCPST',
  'nfeProc.NFe.infNFe.total.ICMSTot.vFCPSTRet',
  'nfeProc.NFe.infNFe.total.ICMSTot.vProd',
  'nfeProc.NFe.infNFe.total.ICMSTot.vFrete',
  'nfeProc.NFe.infNFe.total.ICMSTot.vSeg',
  'nfeProc.NFe.infNFe.total.ICMSTot.vDesc',
  'nfeProc.NFe.infNFe.total.ICMSTot.vII',
  'nfeProc.NFe.infNFe.total.ICMSTot.vIPI',
  'nfeProc.NFe.infNFe.total.ICMSTot.vIPIDevol',
  'nfeProc.NFe.infNFe.total.ICMSTot.vPIS',
  'nfeProc.NFe.infNFe.total.ICMSTot.vCOFINS',
  'nfeProc.NFe.infNFe.total.ICMSTot.vOutro',
  'nfeProc.NFe.infNFe.total.ICMSTot.vNF',
  
  // Pagos
  'nfeProc.NFe.infNFe.pag.detPag.vPag',
  
  // ICMS UF Dest
  'nfeProc.NFe.infNFe.det.imposto.ICMSUFDest.vBCUFDest',
  'nfeProc.NFe.infNFe.det.imposto.ICMSUFDest.vBCFCPUFDest',
  'nfeProc.NFe.infNFe.det.imposto.ICMSUFDest.vICMSUFDest',
  'nfeProc.NFe.infNFe.det.imposto.ICMSUFDest.vICMSUFRemet'
];
